GET http://localhost:3001

###

POST http://localhost:3001/new
Content-Type: application/json

{
    "name":"sheesh"
}

###

GET http://localhost:3001/todos
Content-Type: application/json

{
    "name": "sheesh"
}